/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacyinventorymanagement;

/**
 *
 * @author Bharath Kumar S P
 * @author B Pravena
 * @author Bhuvantej R
 */

import java.sql.*;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

public class AgentsFrame extends javax.swing.JFrame {

    /**
     * Creates new form Agents
     */
    public AgentsFrame() {
        initComponents();
        SelectMed();
    }
    
    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeX = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Title4 = new javax.swing.JLabel();
        Title5 = new javax.swing.JLabel();
        Title6 = new javax.swing.JLabel();
        Title7 = new javax.swing.JLabel();
        Title8 = new javax.swing.JLabel();
        Title9 = new javax.swing.JLabel();
        Title10 = new javax.swing.JLabel();
        a_id = new javax.swing.JTextField();
        a_name = new javax.swing.JTextField();
        a_age = new javax.swing.JTextField();
        a_password = new javax.swing.JTextField();
        a_gender = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        a_phone = new javax.swing.JTextField();
        a_email = new javax.swing.JTextField();
        Title11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AgentTable = new javax.swing.JTable();
        Title12 = new javax.swing.JLabel();
        medBtn = new javax.swing.JLabel();
        companyBtn = new javax.swing.JLabel();
        sellerBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(985, 687));
        jPanel1.setRequestFocusEnabled(false);

        closeX.setFont(new java.awt.Font("Arial Black", 1, 32)); // NOI18N
        closeX.setForeground(new java.awt.Color(255, 153, 153));
        closeX.setText("x");
        closeX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeXMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        Title4.setBackground(new java.awt.Color(255, 255, 255));
        Title4.setFont(new java.awt.Font("High Tower Text", 1, 17)); // NOI18N
        Title4.setForeground(new java.awt.Color(51, 153, 0));
        Title4.setText("ID");

        Title5.setBackground(new java.awt.Color(255, 255, 255));
        Title5.setFont(new java.awt.Font("High Tower Text", 1, 17)); // NOI18N
        Title5.setForeground(new java.awt.Color(51, 153, 0));
        Title5.setText("NAME");

        Title6.setBackground(new java.awt.Color(255, 255, 255));
        Title6.setFont(new java.awt.Font("High Tower Text", 1, 17)); // NOI18N
        Title6.setForeground(new java.awt.Color(51, 153, 0));
        Title6.setText("AGE");

        Title7.setBackground(new java.awt.Color(255, 255, 255));
        Title7.setFont(new java.awt.Font("High Tower Text", 1, 17)); // NOI18N
        Title7.setForeground(new java.awt.Color(51, 153, 0));
        Title7.setText("PASSWORD");

        Title8.setBackground(new java.awt.Color(255, 255, 255));
        Title8.setFont(new java.awt.Font("High Tower Text", 1, 17)); // NOI18N
        Title8.setForeground(new java.awt.Color(51, 153, 0));
        Title8.setText("PHONE");

        Title9.setBackground(new java.awt.Color(255, 255, 255));
        Title9.setFont(new java.awt.Font("High Tower Text", 1, 17)); // NOI18N
        Title9.setForeground(new java.awt.Color(51, 153, 0));
        Title9.setText("GENDER");

        Title10.setBackground(new java.awt.Color(255, 255, 255));
        Title10.setFont(new java.awt.Font("High Tower Text", 1, 17)); // NOI18N
        Title10.setForeground(new java.awt.Color(51, 153, 0));
        Title10.setText("EMAIL");

        a_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_idActionPerformed(evt);
            }
        });

        a_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_nameActionPerformed(evt);
            }
        });

        a_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_ageActionPerformed(evt);
            }
        });

        a_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_passwordActionPerformed(evt);
            }
        });

        a_gender.setBackground(new java.awt.Color(51, 204, 0));
        a_gender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        a_gender.setForeground(new java.awt.Color(255, 255, 255));
        a_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        a_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_genderActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 204, 0));
        btnAdd.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 204, 0));
        btnDelete.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 204, 0));
        btnUpdate.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(0, 204, 0));
        btnClear.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("CLEAR");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        a_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_phoneActionPerformed(evt);
            }
        });

        a_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_emailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title4)
                            .addComponent(Title5))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a_id, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a_name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title6)
                            .addComponent(Title7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a_password, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a_age, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Title8, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(Title9))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(a_phone, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(a_gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(a_email, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))))
                    .addComponent(Title10))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title4)
                    .addComponent(a_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title8)
                    .addComponent(a_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title5)
                    .addComponent(a_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title10)
                    .addComponent(a_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Title6)
                            .addComponent(a_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Title7)
                            .addComponent(a_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Title9)))
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        Title11.setFont(new java.awt.Font("High Tower Text", 1, 26)); // NOI18N
        Title11.setForeground(new java.awt.Color(255, 255, 255));
        Title11.setText("AGENT LIST");

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));

        AgentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Phno", "email", "Gender"
            }
        ));
        AgentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AgentTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );

        Title12.setFont(new java.awt.Font("High Tower Text", 1, 26)); // NOI18N
        Title12.setForeground(new java.awt.Color(255, 255, 255));
        Title12.setText("MANAGE AGENTS");

        medBtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 22)); // NOI18N
        medBtn.setForeground(new java.awt.Color(255, 255, 255));
        medBtn.setText("MEDICINE");
        medBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medBtnMouseClicked(evt);
            }
        });

        companyBtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 22)); // NOI18N
        companyBtn.setForeground(new java.awt.Color(255, 255, 255));
        companyBtn.setText("COMPANY");
        companyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                companyBtnMouseClicked(evt);
            }
        });

        sellerBtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 22)); // NOI18N
        sellerBtn.setForeground(new java.awt.Color(255, 255, 255));
        sellerBtn.setText("Seller");
        sellerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellerBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeX))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(medBtn)
                                    .addComponent(sellerBtn)
                                    .addComponent(companyBtn))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(156, 156, 156)
                    .addComponent(Title11)
                    .addContainerGap(655, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(158, 158, 158)
                    .addComponent(Title12)
                    .addContainerGap(569, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeX)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(medBtn)
                        .addGap(18, 18, 18)
                        .addComponent(companyBtn)
                        .addGap(18, 18, 18)
                        .addComponent(sellerBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(395, 395, 395)
                    .addComponent(Title11)
                    .addContainerGap(261, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(Title12)
                    .addContainerGap(625, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void SelectMed()
    {
        try{
        Con = DriverManager.getConnection("jdbc:derby://localhost:1527/PharmaDb", "User1","User1");
        St = Con.createStatement();
        Rs = St.executeQuery("Select * from User1.AGENTS");
        AgentTable.setModel(DbUtils.resultSetToTableModel(Rs));
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void a_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_passwordActionPerformed

    private void a_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_ageActionPerformed

    private void a_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_nameActionPerformed

    private void a_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_idActionPerformed

    private void a_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_phoneActionPerformed

    private void a_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_emailActionPerformed

    private void a_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_genderActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        try{
            Con = DriverManager.getConnection("jdbc:derby://localhost:1527/PharmaDb", "User1","User1");
            PreparedStatement add = Con.prepareStatement("insert into AGENTS values(?,?,?,?,?,?,?)");
            add.setInt(1, Integer.valueOf(a_id.getText()));
            add.setString(2, a_name.getText());
            add.setInt(3, Integer.valueOf(a_age.getText()));
            add.setString(4, a_password.getText());
            add.setString(5, a_phone.getText());
            add.setString(6, a_gender.getSelectedItem().toString());
            add.setString(7, a_email.getText());
            
            int row = add.executeUpdate();
            SelectMed();
            Con.close(); 
            JOptionPane.showMessageDialog(this, "Agent Added Successfully");
        
        }catch(org.apache.derby.shared.common.error.DerbySQLIntegrityConstraintViolationException e){
            JOptionPane.showMessageDialog(this, "Error: Constraint violation!");
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, "Error: A SQL exception occured");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked

        a_id.setText("");
        a_name.setText("");
        a_age.setText("");
        a_phone.setText("");
        a_password.setText("");
        a_email.setText("");

    }//GEN-LAST:event_btnClearMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked

       if(a_id.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(this, "Enter The Agent ID To be Deleted");
       }
       else{
           try{
               Con = DriverManager.getConnection("jdbc:derby://localhost:1527/PharmaDb", "User1","User1");
               String Id = a_id.getText();
               String Query = "Delete from User1.AGENTS where A_ID="+Id;
               Statement Add = Con.createStatement();
               Add.executeUpdate(Query);
               SelectMed();
               JOptionPane.showMessageDialog(this, "Agent "+Id+" Deleted Successfully");
 
           }catch(org.apache.derby.shared.common.error.DerbySQLIntegrityConstraintViolationException e){
                JOptionPane.showMessageDialog(this, "Error: Constraint violation!");
            }catch(SQLException e)
            {
                JOptionPane.showMessageDialog(this, "Error: A SQL exception occured");
                e.printStackTrace();
            }
    }

    }//GEN-LAST:event_btnDeleteMouseClicked

    private void AgentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgentTableMouseClicked

         DefaultTableModel model = (DefaultTableModel)AgentTable.getModel();
        int Myindex = AgentTable.getSelectedRow();
        a_id.setText(model.getValueAt(Myindex, 0).toString());
        a_name.setText(model.getValueAt(Myindex, 1).toString());
        a_age.setText(model.getValueAt(Myindex, 2).toString());
        a_phone.setText(model.getValueAt(Myindex, 4).toString());
        a_email.setText(model.getValueAt(Myindex, 6).toString());

    }//GEN-LAST:event_AgentTableMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked

        if (a_id.getText().isEmpty() || a_name.getText().isEmpty() || a_age.getText().isEmpty() || a_phone.getText().isEmpty() || a_password.getText().isEmpty() || a_email.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Missing Information! please fillout all the fields");
        }
        else
        {
            try{
               
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/PharmaDb", "User1","User1");
               
                int Id = Integer.valueOf(a_id.getText());
                String retriveId = "Select A_ID from User1.AGENTS where A_ID="+Id; 
                Statement select = Con.createStatement();
                ResultSet row = select.executeQuery(retriveId);

                if(!row.next()){
                    JOptionPane.showMessageDialog(this, "Agent "+Id+" Unavailable! Please enter valid ID to update");
                }else{
                
                
                    String UpdateQuery = "Update User1.AGENTS set A_NAME = '"+a_name.getText()+"'"+",A_AGE = "+a_age.getText()+",A_PHONE = '"+a_phone.getText()+"',A_PASSWORD = '"+a_password.getText()+"',A_GENDER = '"+a_gender.getSelectedItem().toString()+"'"+" where A_ID = "+a_id.getText();
                    Statement Add = Con.createStatement();
                    Add.executeUpdate(UpdateQuery);
                    JOptionPane.showMessageDialog(this, "Agent Updated Successfully");

                    SelectMed();
                }
            }catch(org.apache.derby.shared.common.error.DerbySQLIntegrityConstraintViolationException e){
                JOptionPane.showMessageDialog(this, "Error: check your internet");
            }catch(SQLException e)
            {
                JOptionPane.showMessageDialog(this, "Error: A SQL exception occured");
                e.printStackTrace();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Error: please fill all details correctly!");

            }
            


        }

    }//GEN-LAST:event_btnUpdateMouseClicked

    private void closeXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeXMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeXMouseClicked

    private void sellerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellerBtnMouseClicked

        try{
            new SellingFrame().setVisible(true);
            this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Internal Server Error!");

            e.printStackTrace();
        }

    }//GEN-LAST:event_sellerBtnMouseClicked

    private void companyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyBtnMouseClicked

        try{
            new CompanyFrame().setVisible(true);
            this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Internal Server Error!");

            e.printStackTrace();
        }

    }//GEN-LAST:event_companyBtnMouseClicked

    private void medBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medBtnMouseClicked

        try{
            new MedicineFrame().setVisible(true);
            this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Internal Server Error!");

            e.printStackTrace();
        }

    }//GEN-LAST:event_medBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AgentTable;
    private javax.swing.JLabel Title10;
    private javax.swing.JLabel Title11;
    private javax.swing.JLabel Title12;
    private javax.swing.JLabel Title4;
    private javax.swing.JLabel Title5;
    private javax.swing.JLabel Title6;
    private javax.swing.JLabel Title7;
    private javax.swing.JLabel Title8;
    private javax.swing.JLabel Title9;
    private javax.swing.JTextField a_age;
    private javax.swing.JTextField a_email;
    private javax.swing.JComboBox<String> a_gender;
    private javax.swing.JTextField a_id;
    private javax.swing.JTextField a_name;
    private javax.swing.JTextField a_password;
    private javax.swing.JTextField a_phone;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel closeX;
    private javax.swing.JLabel companyBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel medBtn;
    private javax.swing.JLabel sellerBtn;
    // End of variables declaration//GEN-END:variables
}
